version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - C:/Users/user/Videos/Postgres DB/thevoice2u/postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: matan@absprog.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '8080:80'
    depends_on:
      - db
